### ISSUE TITLE
Docker image uploaded?

### ISSUE THREAD

**Issue by harrisonsp** [owaspsamm/sammwise#1]
I've been looking for something like this! I'm pretty excited to try it out. I see that the README.md file says there is a TODO to upload the Docker image to dockerhub. I've been searching around there and haven't found anything that suggests the image exists yet. I'm wondering when it might be available. Any word?

In the meantime, I will try building the image myself or running it through Node.

**Comment by doublethink** [comment]
There is currently an issue with the docker build as there is no pin on the alpine container.
Will upload to dockerhub when the build is successful

**Comment by doublethink** [comment]
Pinned the container to the latest node LTS, I think there is still some work to get the nextjs version up to something more recent.
I have push the (working) image to dockerhub here: https://hub.docker.com/r/stephenmorgan/owasp-sammwise
