### ISSUE TITLE
Outdated docker instance on docker hub

### ISSUE THREAD

**Issue by vdbaan** [owaspsamm/sammwise#8]
The docker image on docker hub is outdated.
This is visible as the order of the implementation elements on the results page in the "Maturity by Practice" overview is incorrect.

Please push an updated version of the docker image

**Comment by doublethink** [comment]
I no longer have access to the Azure DevOps pipeline and it has been on my backlog to recreate.
Will commit to fixing this, this month

**Comment by doublethink** [comment]
I have pushed the latest version but will keep this ticket open because the project I want to integrate GH Actions - but will upgrade version first

**Comment by doublethink** [comment]
I have insufficient permissions to add secrets, will create feature to coordinate this outside this issue.
